/**
 * auto-po
 *
 * Cron-driven. For each active branch, finds ingredients below their reorder
 * level and creates a draft purchase_order grouped by supplier. Skips if a
 * draft PO already exists for that supplier today.
 */
import { serve } from 'https://deno.land/std@0.208.0/http/server.ts'
import { corsHeaders, handleOptions } from '../_shared/cors.ts'
import { adminClient } from '../_shared/supabase.ts'
import { requireServiceRole } from '../_shared/auth.ts'

serve(async (req) => {
  const pre = handleOptions(req); if (pre) return pre
  const authErr = requireServiceRole(req)
  if (authErr) return authErr

  const r = adminClient()
  const rest = (r as unknown as { schema: (n: string) => ReturnType<typeof adminClient> }).schema('restaurant')

  const { data: branches } = await rest.from('branch').select('id, name').eq('status', 'active')
  let created = 0

  for (const b of (branches ?? [])) {
    const { data: ings } = await rest.from('ingredient')
      .select('id, supplier_id, current_stock, reorder_level, cost_per_unit, name')
      .eq('branch_id', b.id)
      .eq('is_active', true)
    const low = (ings ?? []).filter((i: { reorder_level: number; current_stock: number }) =>
      Number(i.reorder_level ?? 0) > 0 && Number(i.current_stock) < Number(i.reorder_level))

    // Group by supplier_id (null bucket allowed = "no supplier yet")
    const bySupplier = new Map<string, Array<{ id: string; current_stock: number; reorder_level: number; cost_per_unit: number; name: string }>>()
    for (const i of low as Array<{ id: string; supplier_id: string | null; current_stock: number; reorder_level: number; cost_per_unit: number; name: string }>) {
      const key = i.supplier_id ?? '__none__'
      const arr = bySupplier.get(key) ?? []
      arr.push({ id: i.id, current_stock: Number(i.current_stock), reorder_level: Number(i.reorder_level ?? 0), cost_per_unit: Number(i.cost_per_unit ?? 0), name: i.name })
      bySupplier.set(key, arr)
    }

    for (const [supplierKey, items] of bySupplier) {
      const supplier_id = supplierKey === '__none__' ? null : supplierKey
      // Skip if a draft PO already exists for this supplier today
      const today = new Date(); today.setHours(0, 0, 0, 0)
      const { count } = await rest.from('purchase_order')
        .select('id', { count: 'exact', head: true })
        .eq('branch_id', b.id)
        .eq('supplier_id', supplier_id)
        .eq('status', 'draft')
        .gte('created_at', today.toISOString())
      if ((count ?? 0) > 0) continue

      const total = items.reduce((s, x) => s + (Math.max(1, x.reorder_level * 2 - x.current_stock)) * x.cost_per_unit, 0)
      const { data: po } = await rest.from('purchase_order').insert({
        branch_id: b.id,
        supplier_id,
        status: 'draft',
        total_cost: total,
        notes: `Auto-generated by cron. ${items.length} low-stock ingredients.`,
      }).select('id').single()
      if (!po) continue
      const lines = items.map((x) => ({
        po_id: (po as { id: string }).id,
        ingredient_id: x.id,
        ordered_qty: Math.max(1, x.reorder_level * 2 - x.current_stock),
        received_qty: 0,
        unit_cost: x.cost_per_unit,
      }))
      if (lines.length > 0) await rest.from('purchase_order_line').insert(lines)
      created++
    }
  }

  return new Response(JSON.stringify({ ok: true, draft_pos_created: created }), {
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
})
