-- ============================================================================
-- 0138 — Wrap auth.uid() / auth.jwt() / auth.role() in (select …) in RLS policies
--
-- Audit item #13 from the 2026-06-04 perf review. The classic Supabase RLS
-- perf footgun: bare auth.uid() is re-evaluated per row by the planner,
-- but (select auth.uid()) is hoisted to a single scalar evaluation per
-- statement. On a 100k-row matches scan this is ~50x speedup on RLS-
-- filtered reads. Generated by sweeping pg_policies and rewriting the 77
-- policies that had unwrapped occurrences (pre-filtered to skip those with
-- any already-wrapped instance — preventing double-wrap).
--
-- Semantics identical: auth.* are STABLE; (select …) is hoisted by the
-- planner so the function still runs exactly once per statement.
-- ============================================================================

ALTER POLICY "ai_chat_select_self" ON public.ai_chat_messages
  USING ((user_id = (select auth.uid())));

ALTER POLICY "audit_log_select_own" ON public.audit_log
  USING ((subject_id = (select auth.uid())));

ALTER POLICY "auth_events_admin_select" ON public.auth_events
  USING ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = (select auth.uid())) AND (p.role = 'admin'::text)))));

ALTER POLICY "crl_select_self" ON public.chat_rate_limits
  USING ((user_id = (select auth.uid())));

ALTER POLICY "cold_start_select_own_hm" ON public.cold_start_queue
  USING ((EXISTS ( SELECT 1
   FROM (roles r
     JOIN hiring_managers hm ON ((hm.id = r.hiring_manager_id)))
  WHERE ((r.id = cold_start_queue.role_id) AND (hm.profile_id = (select auth.uid()))))));

ALTER POLICY "companies_select_creator" ON public.companies
  USING (((created_by = (select auth.uid())) AND can_insert_company()));

ALTER POLICY "companies_update_creator_unverified" ON public.companies
  USING (((verified = false) AND ((created_by = (select auth.uid())) OR (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = (select auth.uid())) AND (p.email = companies.primary_hr_email)))))))
  WITH CHECK (((verified = false) AND ((created_by = (select auth.uid())) OR (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = (select auth.uid())) AND (p.email = companies.primary_hr_email)))))));

ALTER POLICY "link_req_hm_self" ON public.company_hm_link_requests
  USING ((EXISTS ( SELECT 1
   FROM hiring_managers hm
  WHERE ((hm.id = company_hm_link_requests.hm_id) AND (hm.profile_id = (select auth.uid()))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM hiring_managers hm
  WHERE ((hm.id = company_hm_link_requests.hm_id) AND (hm.profile_id = (select auth.uid()))))));

ALTER POLICY "link_req_hr_manage" ON public.company_hm_link_requests
  USING ((EXISTS ( SELECT 1
   FROM (companies c
     JOIN profiles p ON ((p.email = c.primary_hr_email)))
  WHERE ((c.id = company_hm_link_requests.company_id) AND (p.id = (select auth.uid())) AND (p.role = 'hr_admin'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM (companies c
     JOIN profiles p ON ((p.email = c.primary_hr_email)))
  WHERE ((c.id = company_hm_link_requests.company_id) AND (p.id = (select auth.uid())) AND (p.role = 'hr_admin'::text)))));

ALTER POLICY "consult_insert_self" ON public.consult_bookings
  WITH CHECK ((profile_id = (select auth.uid())));

ALTER POLICY "consult_select_own" ON public.consult_bookings
  USING (((profile_id = (select auth.uid())) OR is_admin()));

ALTER POLICY "data_requests_insert_self" ON public.data_requests
  WITH CHECK ((user_id = (select auth.uid())));

ALTER POLICY "data_requests_select_self" ON public.data_requests
  USING ((user_id = (select auth.uid())));

ALTER POLICY "emp_select_self" ON public.extra_match_purchases
  USING ((user_id = (select auth.uid())));

ALTER POLICY "feedback_insert_self" ON public.feedback_submissions
  WITH CHECK (((select auth.uid()) = from_user_id));

ALTER POLICY "feedback_select_own" ON public.feedback_submissions
  USING ((((select auth.uid()) = from_user_id) OR ((select auth.uid()) = to_user_id) OR is_admin()));

ALTER POLICY "hm_insert_self_as_hr" ON public.hiring_managers
  WITH CHECK (((profile_id = (select auth.uid())) AND (EXISTS ( SELECT 1
   FROM (companies c
     JOIN profiles p ON ((p.id = (select auth.uid()))))
  WHERE ((c.id = hiring_managers.company_id) AND (c.primary_hr_email = p.email) AND (p.role = 'hr_admin'::text))))));

ALTER POLICY "hm_select_hr_floating" ON public.hiring_managers
  USING (((company_id IS NULL) AND (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = (select auth.uid())) AND (p.role = ANY (ARRAY['hr_admin'::text, 'admin'::text])))))));

ALTER POLICY "hm_select_self" ON public.hiring_managers
  USING ((profile_id = (select auth.uid())));

ALTER POLICY "hm_update_self" ON public.hiring_managers
  USING ((profile_id = (select auth.uid())))
  WITH CHECK ((profile_id = (select auth.uid())));

ALTER POLICY "interviews_select_hm" ON public.interviews
  USING ((EXISTS ( SELECT 1
   FROM ((matches m
     JOIN roles r ON ((r.id = m.role_id)))
     JOIN hiring_managers hm ON ((hm.id = r.hiring_manager_id)))
  WHERE ((m.id = interviews.match_id) AND (hm.profile_id = (select auth.uid()))))));

ALTER POLICY "interviews_select_talent" ON public.interviews
  USING ((EXISTS ( SELECT 1
   FROM (matches m
     JOIN talents t ON ((t.id = m.talent_id)))
  WHERE ((m.id = interviews.match_id) AND (t.profile_id = (select auth.uid()))))));

ALTER POLICY "hm own draft" ON public.job_posting_drafts
  USING ((hm_id = ( SELECT hiring_managers.id
   FROM hiring_managers
  WHERE (hiring_managers.profile_id = (select auth.uid())))));

ALTER POLICY "yf_select_own" ON public.life_chart_yearly_fortune
  USING ((((select auth.uid()) = profile_id) OR is_admin()));

ALTER POLICY "read_own_feedback_events" ON public.match_feedback_events
  USING (((EXISTS ( SELECT 1
   FROM (matches m
     JOIN talents t ON ((t.id = m.talent_id)))
  WHERE ((m.id = match_feedback_events.match_id) AND (t.profile_id = (select auth.uid()))))) OR (EXISTS ( SELECT 1
   FROM ((matches m
     JOIN roles r ON ((r.id = m.role_id)))
     JOIN hiring_managers hm ON ((hm.id = r.hiring_manager_id)))
  WHERE ((m.id = match_feedback_events.match_id) AND (hm.profile_id = (select auth.uid())))))));

ALTER POLICY "admin_all_lifecycle" ON public.match_lifecycle
  USING ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = (select auth.uid())) AND (p.role = 'admin'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = (select auth.uid())) AND (p.role = 'admin'::text)))));

ALTER POLICY "read_own_lifecycle" ON public.match_lifecycle
  USING (((EXISTS ( SELECT 1
   FROM (matches m
     JOIN talents t ON ((t.id = m.talent_id)))
  WHERE ((m.id = match_lifecycle.match_id) AND (t.profile_id = (select auth.uid()))))) OR (EXISTS ( SELECT 1
   FROM ((matches m
     JOIN roles r ON ((r.id = m.role_id)))
     JOIN hiring_managers hm ON ((hm.id = r.hiring_manager_id)))
  WHERE ((m.id = match_lifecycle.match_id) AND (hm.profile_id = (select auth.uid())))))));

ALTER POLICY "admin_all_outcomes" ON public.match_outcomes
  USING ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = (select auth.uid())) AND (p.role = 'admin'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = (select auth.uid())) AND (p.role = 'admin'::text)))));

ALTER POLICY "match_queue_service_only" ON public.match_queue
  USING (((select auth.role()) = 'service_role'::text));

ALTER POLICY "matches_select_hm" ON public.matches
  USING (((status <> 'pending_approval'::text) AND (EXISTS ( SELECT 1
   FROM (roles r
     JOIN hiring_managers hm ON ((hm.id = r.hiring_manager_id)))
  WHERE ((r.id = matches.role_id) AND (hm.profile_id = (select auth.uid())))))));

ALTER POLICY "matches_select_hr" ON public.matches
  USING (((status <> 'pending_approval'::text) AND (EXISTS ( SELECT 1
   FROM (((roles r
     JOIN hiring_managers hm ON ((hm.id = r.hiring_manager_id)))
     JOIN companies c ON ((c.id = hm.company_id)))
     JOIN profiles p ON ((p.email = c.primary_hr_email)))
  WHERE ((r.id = matches.role_id) AND (p.id = (select auth.uid())) AND (p.role = 'hr_admin'::text))))));

ALTER POLICY "matches_select_talent" ON public.matches
  USING (((status <> 'pending_approval'::text) AND (EXISTS ( SELECT 1
   FROM talents t
  WHERE ((t.id = matches.talent_id) AND (t.profile_id = (select auth.uid())))))));

ALTER POLICY "matches_update_talent" ON public.matches
  USING ((EXISTS ( SELECT 1
   FROM talents t
  WHERE ((t.id = matches.talent_id) AND (t.profile_id = (select auth.uid()))))));

ALTER POLICY "nn_atom_embed_admin" ON public.nn_atom_embeddings
  USING (((select auth.role()) = 'service_role'::text))
  WITH CHECK (((select auth.role()) = 'service_role'::text));

ALTER POLICY "notifications_select_self" ON public.notifications
  USING ((user_id = (select auth.uid())));

ALTER POLICY "notifications_update_self" ON public.notifications
  USING ((user_id = (select auth.uid())))
  WITH CHECK ((user_id = (select auth.uid())));

ALTER POLICY "nudge_history_self_select" ON public.nudge_history
  USING ((talent_id IN ( SELECT talents.id
   FROM talents
  WHERE (talents.profile_id = (select auth.uid())))));

ALTER POLICY "pp_select_self" ON public.point_purchases
  USING ((user_id = (select auth.uid())));

ALTER POLICY "points_select_own" ON public.point_transactions
  USING ((((select auth.uid()) = user_id) OR is_admin()));

ALTER POLICY "profiles_insert_self" ON public.profiles
  WITH CHECK (((select auth.uid()) = id));

ALTER POLICY "profiles_select_self" ON public.profiles
  USING (((select auth.uid()) = id));

ALTER POLICY "profiles_update_self" ON public.profiles
  USING (((select auth.uid()) = id))
  WITH CHECK ((((select auth.uid()) = id) AND (role = ANY (ARRAY['talent'::text, 'hiring_manager'::text, 'hr_admin'::text])) AND (is_banned = false)));

ALTER POLICY "ref_insert_self" ON public.referrals
  WITH CHECK (((select auth.uid()) = referrer_id));

ALTER POLICY "ref_select_own" ON public.referrals
  USING ((((select auth.uid()) = referrer_id) OR ((select auth.uid()) = referred_user_id) OR is_admin()));

ALTER POLICY "rme_select_admin" ON public.role_moderation_events
  USING ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = (select auth.uid())) AND (p.role = 'admin'::text)))));

ALTER POLICY "rme_select_owner" ON public.role_moderation_events
  USING ((EXISTS ( SELECT 1
   FROM (roles r
     JOIN hiring_managers hm ON ((hm.id = r.hiring_manager_id)))
  WHERE ((r.id = role_moderation_events.role_id) AND (hm.profile_id = (select auth.uid()))))));

ALTER POLICY "roles_insert_hm" ON public.roles
  WITH CHECK ((EXISTS ( SELECT 1
   FROM hiring_managers hm
  WHERE ((hm.id = roles.hiring_manager_id) AND (hm.profile_id = (select auth.uid()))))));

ALTER POLICY "roles_select_hm" ON public.roles
  USING ((EXISTS ( SELECT 1
   FROM hiring_managers hm
  WHERE ((hm.id = roles.hiring_manager_id) AND (hm.profile_id = (select auth.uid()))))));

ALTER POLICY "roles_update_hm" ON public.roles
  USING ((EXISTS ( SELECT 1
   FROM hiring_managers hm
  WHERE ((hm.id = roles.hiring_manager_id) AND (hm.profile_id = (select auth.uid()))))));

ALTER POLICY "skill_taxonomy_admin_write" ON public.skill_taxonomy
  USING (((select auth.role()) = 'service_role'::text))
  WITH CHECK (((select auth.role()) = 'service_role'::text));

ALTER POLICY "support_tickets_admin_all" ON public.support_tickets
  USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = (select auth.uid())) AND (profiles.role = 'admin'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = (select auth.uid())) AND (profiles.role = 'admin'::text)))));

ALTER POLICY "support_tickets_user_insert" ON public.support_tickets
  WITH CHECK (((select auth.uid()) = user_id));

ALTER POLICY "support_tickets_user_select" ON public.support_tickets
  USING (((select auth.uid()) = user_id));

ALTER POLICY "talent_documents_insert_own" ON public.talent_documents
  WITH CHECK ((talent_id IN ( SELECT talents.id
   FROM talents
  WHERE (talents.profile_id = (select auth.uid())))));

ALTER POLICY "talents_insert_self" ON public.talents
  WITH CHECK ((profile_id = (select auth.uid())));

ALTER POLICY "talents_select_self" ON public.talents
  USING ((profile_id = (select auth.uid())));

ALTER POLICY "talents_update_self" ON public.talents
  USING ((profile_id = (select auth.uid())))
  WITH CHECK ((profile_id = (select auth.uid())));

ALTER POLICY "upr_select_self" ON public.urgent_priority_requests
  USING ((user_id = (select auth.uid())));

ALTER POLICY "user_tags_select_self" ON public.user_tags
  USING ((user_id = (select auth.uid())));

ALTER POLICY "rst_anon_branch" ON restaurant.branch
  USING (((select auth.role()) = 'anon'::text));

ALTER POLICY "rst_anon_insert_kitchen_ticket" ON restaurant.kitchen_ticket
  WITH CHECK (((select auth.role()) = 'anon'::text));

ALTER POLICY "rst_anon_menu_category" ON restaurant.menu_category
  USING (((select auth.role()) = 'anon'::text));

ALTER POLICY "rst_anon_menu_item" ON restaurant.menu_item
  USING ((((select auth.role()) = 'anon'::text) AND (is_active = true)));

ALTER POLICY "rst_anon_modifier" ON restaurant.modifier
  USING ((((select auth.role()) = 'anon'::text) AND (is_active = true)));

ALTER POLICY "rst_all_authenticated" ON restaurant.notification
  USING (((select auth.role()) = 'authenticated'::text))
  WITH CHECK (((select auth.role()) = 'authenticated'::text));

ALTER POLICY "rst_anon_insert_order_item" ON restaurant.order_item
  WITH CHECK (((select auth.role()) = 'anon'::text));

ALTER POLICY "rst_anon_read_order_item" ON restaurant.order_item
  USING (((select auth.role()) = 'anon'::text));

ALTER POLICY "rst_anon_insert_orders" ON restaurant.orders
  WITH CHECK (((select auth.role()) = 'anon'::text));

ALTER POLICY "rst_anon_read_orders" ON restaurant.orders
  USING (((select auth.role()) = 'anon'::text));

ALTER POLICY "rst_org_member_insert" ON restaurant.org_member
  WITH CHECK (((select auth.role()) = 'authenticated'::text));

ALTER POLICY "rst_org_insert" ON restaurant.organization
  WITH CHECK (((select auth.role()) = 'authenticated'::text));

ALTER POLICY "rst_anon_promotion" ON restaurant.promotion
  USING ((((select auth.role()) = 'anon'::text) AND (is_active = true)));

ALTER POLICY "rst_all_authenticated" ON restaurant.promotion_redemption
  USING (((select auth.role()) = 'authenticated'::text))
  WITH CHECK (((select auth.role()) = 'authenticated'::text));

ALTER POLICY "rst_anon_table" ON restaurant.restaurant_table
  USING (((select auth.role()) = 'anon'::text));

ALTER POLICY "rst_all_authenticated" ON restaurant.stock_take
  USING (((select auth.role()) = 'authenticated'::text))
  WITH CHECK (((select auth.role()) = 'authenticated'::text));

ALTER POLICY "rst_all_authenticated" ON restaurant.stock_take_line
  USING (((select auth.role()) = 'authenticated'::text))
  WITH CHECK (((select auth.role()) = 'authenticated'::text));

ALTER POLICY "rst_all_authenticated" ON restaurant.waiter_section
  USING (((select auth.role()) = 'authenticated'::text))
  WITH CHECK (((select auth.role()) = 'authenticated'::text));
